/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
static yyconst short int yy_accept[262] =
    {   0,
        0,    0,   19,   17,    4,   16,   17,    9,    1,    6,
        9,    2,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    4,    0,   14,    0,
        0,    0,    0,    0,    9,    0,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,   14,    0,    0,    0,
        0,    0,    0,    0,    0,    9,    9,    9,    9,    9,
        3,    9,    9,    9,    9,    0,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    0,    0,    8,
        0,    7,    0,    0,    0,   13,    0,    0,    0,    9,

        9,    9,    9,    9,    9,    9,    9,    0,    9,    9,
        0,    0,    9,    0,    0,    9,    9,    0,    9,    9,
        0,   13,    0,    0,    0,    9,    9,    9,    9,    9,
        9,    9,    0,    9,    9,    0,    0,    0,    0,    0,
        0,    9,    9,    0,    9,    0,    0,   11,    0,    9,
        9,    9,    0,    0,    9,    9,    0,    9,    9,    0,
        5,    0,    0,   10,    0,    9,    0,    0,   15,   11,
        9,    9,    0,    0,    0,    9,    0,    0,    9,    5,
       10,    0,    0,   15,    9,    0,   12,    0,    0,    0,
        9,    0,    0,    9,   12,    0,    0,    9,    0,    0,

        9,    0,    0,    9,    0,    0,    0,    0,    9,    0,
        0,    0,    0,    0,    9,    0,    0,    0,    0,    0,
        0,    9,    0,   12,    0,    0,    0,    0,    9,   12,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    5,    0,    0,    0,    5,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    6,    1,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    9,
       10,   11,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,   13,    1,   14,   12,   15,   16,

       17,   18,   19,   20,   21,   12,   12,   22,   23,   24,
       25,   26,   12,   27,   28,   29,   30,   12,   31,   12,
       32,   33,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[34] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    2,    3,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2
    } ;

static yyconst short int yy_base[279] =
    {   0,
        0,    0,  618,  619,  615,  619,   32,  619,   33,   35,
       36,   37,   39,   40,   43,   46,   52,   61,   62,   65,
       74,   71,   80,   83,   81,   92,  614,   50,  613,   96,
       66,   49,   97,   98,  104,  114,  110,  115,  119,  120,
      121,  124,  122,  134,  144,  145,  147,  151,  154,  157,
      163,  125,  160,  161,  164,  167,  612,  177,  126,  131,
      178,   34,  190,  609,  607,  186,  191,  196,  195,  197,
      198,  202,  201,  208,  211,  584,  220,  221,  224,  223,
      226,  227,  236,  240,  242,  243,  249,  252,  256,  619,
      258,  619,  259,  587,  605,  606,  602,  260,  269,  262,

      266,  273,  275,  277,  279,  282,  292,  589,  289,  294,
      299,  303,  309,  310,  311,  312,  315,  590,  316,  321,
      585,  601,  330,  598,  596,  326,  336,  337,  338,  340,
      343,  347,  582,  352,  353,  354,  595,  593,  366,  593,
      591,  363,  367,  568,  372,  284,  590,  591,  587,  373,
      376,  377,  379,  389,  393,  395,  574,  400,  397,  586,
      587,  583,  583,  584,  580,  407,  567,  409,  581,  580,
      406,  416,  417,  577,  575,  423,  552,  547,  426,  575,
      574,  545,  558,  571,  427,  568,  569,  565,  542,  548,
      429,  539,  544,  433,  554,  534,  529,  432,  519,  512,

      438,  504,  502,  439,  442,  492,  510,  505,  448,  449,
      461,  485,  470,  481,  458,  470,  491,  486,  470,  461,
      450,  454,  472,  465,  442,  423,  413,  399,  468,  413,
      376,  377,  360,  469,  478,  379,  344,  483,  356,  339,
      327,  321,  320,  280,  260,  223,  222,  233,  193,  182,
      178,  166,  165,  163,   84,   89,   82,   65,   70,   62,
      619,  487,   55,  491,  497,  502,  507,  512,  517,  522,
      527,  532,  537,  542,  547,  552,  557,  562
    } ;

static yyconst short int yy_def[279] =
    {   0,
      261,    1,  261,  261,  261,  261,  261,  261,  261,  261,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  261,  261,  261,  261,
      263,  261,  261,  261,  262,  261,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  261,  263,  264,  264,
      261,  261,  261,  265,  266,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  261,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  261,  264,  261,
      261,  261,  261,  261,  265,  261,  266,  261,  261,  262,

      262,  262,  262,  262,  262,  262,  262,  261,  262,  262,
      261,  261,  262,  261,  261,  262,  262,  261,  262,  262,
      261,  261,  261,  267,  268,  262,  262,  262,  262,  262,
      262,  262,  261,  262,  262,  261,  269,  270,  261,  271,
      272,  262,  262,  261,  262,  261,  267,  261,  268,  262,
      262,  262,  261,  261,  262,  262,  261,  262,  262,  269,
      261,  270,  271,  261,  272,  262,  261,  261,  261,  261,
      262,  262,  261,  273,  274,  262,  261,  261,  262,  261,
      261,  261,  261,  261,  262,  273,  261,  274,  261,  261,
      262,  261,  261,  262,  261,  261,  261,  262,  261,  261,

      262,  261,  261,  262,  261,  261,  261,  261,  262,  261,
      261,  261,  261,  261,  262,  261,  275,  276,  261,  261,
      261,  262,  275,  261,  276,  261,  261,  261,  262,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  277,  278,
      261,  261,  277,  261,  278,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
        0,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261
    } ;

static yyconst short int yy_nxt[653] =
    {   0,
        4,    5,    6,    4,    4,    4,    7,    8,    9,    4,
       10,   11,    4,   12,   13,   14,   11,   11,   11,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   11,   11,   28,   30,   93,   32,   34,   34,   31,
       34,   34,   29,   33,   34,   36,   36,   34,   36,   36,
       32,   28,   36,   34,   94,   36,   59,   33,   37,   40,
       29,   36,   34,   34,   39,   38,   34,   58,   42,   41,
       36,   36,   34,   43,   36,   34,   44,   45,  205,   60,
       36,   34,   34,   36,   34,  260,   46,   49,  205,   36,
       36,   47,   36,   34,   48,  259,   52,   30,   61,   34,

       50,   36,   31,   62,   54,   34,   51,   36,   55,  258,
      257,   34,   56,   36,   53,   63,   34,   64,   65,   36,
       34,   34,   34,   34,   36,   34,   34,   88,   36,   36,
       36,   36,   91,   36,   36,   34,   90,   70,   66,   67,
       69,   92,   71,   36,   72,   34,   34,   73,   34,   68,
       76,   83,   34,   36,   36,   34,   36,   74,   34,   75,
       36,   34,   34,   36,   34,   34,   36,   77,   34,   36,
       36,   79,   36,   36,   78,   80,   36,   82,   58,   61,
       86,  256,   87,  255,   62,   84,  254,   98,   85,   81,
       60,   63,   34,   64,   65,   99,   34,   34,   34,   34,

       36,  253,   34,   34,   36,   36,   36,   36,  252,   34,
       36,   36,   34,  102,  103,  104,  105,   36,  100,  101,
       36,   34,   34,  251,  111,   34,  106,   34,  114,   36,
       36,  107,  112,   36,  248,   36,  115,   34,  109,   80,
      110,   34,  113,   34,   34,   36,  250,  249,  118,   36,
       34,   36,   36,   88,  116,  117,   80,   88,   36,   91,
       93,   98,   90,   34,  244,  119,   90,   34,   92,   99,
      123,   36,  124,  125,   34,   36,  111,  120,   34,   94,
       34,  248,   36,   34,  112,  168,   36,  127,   36,  126,
       34,   36,  128,   34,  169,   34,  129,  132,   36,  131,

      111,   36,  130,   36,  136,   80,  137,  138,  112,  134,
       34,  114,  139,   34,  140,  141,   34,   34,   36,  115,
      135,   36,   34,  244,   36,   36,  247,   34,  142,  145,
       36,  123,  143,  124,  125,   36,  130,   34,   34,   34,
      130,  153,  246,  244,   34,   36,   36,   36,   34,  154,
      150,  152,   36,   34,   34,  136,   36,  137,  138,  244,
      151,   36,   36,  156,   34,  130,  155,  139,   34,  140,
      141,  242,   36,   34,   34,  158,   36,   34,   34,  159,
      153,   36,   36,  166,  241,   36,   36,  237,  154,  172,
      173,   80,  174,  175,   34,   80,   34,  130,   34,  171,

      236,  153,   36,  205,   36,  178,   36,   34,   34,  154,
      168,  130,  182,  179,  230,   36,   36,   34,  173,  169,
      174,  175,  176,  233,   34,   36,  185,   34,   34,  232,
       34,   80,   36,   34,   34,   36,   36,  130,   36,   34,
       34,   36,   36,  210,  231,  194,  224,   36,   36,   34,
      210,  211,  191,  201,  198,   34,  204,   36,  211,   34,
      209,  130,  216,   36,  217,  218,  230,   36,  215,  234,
      234,  216,  222,  217,  218,  224,  228,  235,  235,  238,
      227,  239,  240,  226,  238,  229,  239,  240,   35,   35,
      224,   35,   89,   89,  224,  221,   89,   95,   95,   95,

      220,   95,   97,   97,   97,  219,   97,  147,  147,  147,
      214,  147,  149,  149,  149,  213,  149,  160,  160,  160,
      212,  160,  162,  162,  162,  208,  162,  163,  163,  163,
      207,  163,  165,  165,  165,  206,  165,  186,  186,  186,
      205,  186,  188,  188,  188,  203,  188,  223,  223,  223,
      202,  223,  225,  225,  225,  195,  225,  243,  243,  243,
      200,  243,  245,  245,  245,  199,  245,  197,  196,  187,
      195,  187,  184,  193,  192,  181,  180,  190,  189,  187,
      187,  170,  184,  183,  164,  181,  164,  161,  180,  161,
      177,  148,  170,  148,  167,  164,  164,  161,  161,  157,

      148,  148,  122,  146,  144,  133,   96,  122,   96,  121,
      108,   96,   96,   57,   57,   27,   27,  261,    3,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261
    } ;

static yyconst short int yy_chk[653] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    9,   62,   10,   11,   12,    9,
       13,   14,    7,   10,   15,   11,   12,   16,   13,   14,
       32,   28,   15,   17,   62,   16,  263,   32,   12,   15,
       28,   17,   18,   19,   14,   13,   20,   31,   16,   15,
       18,   19,   22,   16,   20,   21,   17,   18,  260,   31,
       22,   23,   25,   21,   24,  259,   19,   22,  258,   23,
       25,   20,   24,   26,   21,  257,   24,   30,   33,   34,

       23,   26,   30,   33,   25,   35,   23,   34,   25,  256,
      255,   37,   26,   35,   24,   36,   38,   36,   36,   37,
       39,   40,   41,   43,   38,   42,   52,   59,   39,   40,
       41,   43,   60,   42,   52,   44,   59,   41,   37,   38,
       40,   60,   42,   44,   43,   45,   46,   44,   47,   39,
       46,   52,   48,   45,   46,   49,   47,   44,   50,   45,
       48,   53,   54,   49,   51,   55,   50,   47,   56,   53,
       54,   49,   51,   55,   48,   49,   56,   51,   58,   61,
       55,  254,   56,  253,   61,   53,  252,   66,   54,   50,
       58,   63,   67,   63,   63,   66,   69,   68,   70,   71,

       67,  251,   73,   72,   69,   68,   70,   71,  250,   74,
       73,   72,   75,   69,   70,   72,   73,   74,   67,   68,
       75,   77,   78,  249,   80,   79,   74,   81,   82,   77,
       78,   75,   80,   79,  248,   81,   82,   83,   77,   78,
       79,   84,   81,   85,   86,   83,  247,  246,   86,   84,
       87,   85,   86,   88,   83,   85,   84,   89,   87,   91,
       93,   98,   88,  100,  245,   86,   89,  101,   91,   98,
       99,  100,   99,   99,  102,  101,  103,   87,  104,   93,
      105,  244,  102,  106,  103,  146,  104,  101,  105,  100,
      109,  106,  102,  107,  146,  110,  103,  106,  109,  105,

      111,  107,  104,  110,  112,  107,  112,  112,  111,  109,
      113,  114,  115,  116,  115,  115,  117,  119,  113,  114,
      110,  116,  120,  243,  117,  119,  242,  126,  116,  119,
      120,  123,  117,  123,  123,  126,  113,  127,  128,  129,
      120,  130,  241,  240,  131,  127,  128,  129,  132,  130,
      126,  129,  131,  134,  135,  136,  132,  136,  136,  239,
      127,  134,  135,  132,  142,  128,  131,  139,  143,  139,
      139,  237,  142,  145,  150,  134,  143,  151,  152,  135,
      153,  145,  150,  143,  236,  151,  152,  233,  153,  151,
      154,  142,  154,  154,  155,  152,  156,  145,  159,  150,

      232,  158,  155,  231,  156,  158,  159,  171,  166,  158,
      168,  155,  166,  159,  230,  171,  166,  172,  173,  168,
      173,  173,  156,  228,  176,  172,  171,  179,  185,  227,
      191,  172,  176,  198,  194,  179,  185,  176,  191,  201,
      204,  198,  194,  205,  226,  185,  225,  201,  204,  209,
      210,  205,  179,  194,  191,  222,  198,  209,  210,  215,
      204,  201,  211,  222,  211,  211,  224,  215,  209,  229,
      234,  216,  215,  216,  216,  223,  221,  229,  234,  235,
      220,  235,  235,  219,  238,  222,  238,  238,  262,  262,
      218,  262,  264,  264,  217,  214,  264,  265,  265,  265,

      213,  265,  266,  266,  266,  212,  266,  267,  267,  267,
      208,  267,  268,  268,  268,  207,  268,  269,  269,  269,
      206,  269,  270,  270,  270,  203,  270,  271,  271,  271,
      202,  271,  272,  272,  272,  200,  272,  273,  273,  273,
      199,  273,  274,  274,  274,  197,  274,  275,  275,  275,
      196,  275,  276,  276,  276,  195,  276,  277,  277,  277,
      193,  277,  278,  278,  278,  192,  278,  190,  189,  188,
      187,  186,  184,  183,  182,  181,  180,  178,  177,  175,
      174,  170,  169,  167,  165,  164,  163,  162,  161,  160,
      157,  149,  148,  147,  144,  141,  140,  138,  137,  133,

      125,  124,  122,  121,  118,  108,   97,   96,   95,   94,
       76,   65,   64,   57,   29,   27,    5,    3,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tag_parser.l"
#define INITIAL 0
/* Lex Program. */
#line 4 "tag_parser.l"
	/*contains declaration of all the tokens in the yacc program*/
#include "y.tab.h"
	/*variables used while validation*/
int a_valid = 0,end_tag1=0;
/*Regular expressions to be matched while performaing lexical analysis*/
/*RE for whitespaces*/
/*RE for letters*/
/*RE for digits*/
/*RE for identifiers*/
/*RE for content inside <a> tag*/
/*attributes of <a> tag*/
/*attribute list for <a> tag*/
/*attributes of <img> tag*/
/*attribute list for image tag*/
/*RE for attribute value*/
//end of declaration section
#line 612 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 44 "tag_parser.l"

	/*translation rules
	pattern {
				action
			}
	*/

	/* "<"" will be matched here.*/
#line 772 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 262 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 619 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 "tag_parser.l"
{ 	printf("\n [Parsing]: %s\n", yytext);
		return START_ANGLE_BRACKET;} 
	YY_BREAK
/* "a" will be matched here.*/
case 2:
YY_RULE_SETUP
#line 56 "tag_parser.l"
{ 		/*a_valid is used for validating content of <a> tag.*/
		a_valid =1;
		printf("\n [Parsing]: %s\n", yytext);
		return A_TAG;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "tag_parser.l"
{ printf("\n [Parsing]: %s\n", yytext);
		return IMG_TAG;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "tag_parser.l"
{;}
	YY_BREAK
/*anchor tag's attribute is matched here*/
case 5:
YY_RULE_SETUP
#line 67 "tag_parser.l"
{
											//valid attribute for a tag
											printf("\n [Parsing]: %s\n", yytext);
								 			return A_ATTRIBUTE;	
										}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "tag_parser.l"
{ 	/*end_tag1 is used for validating content of <a> tag.*/
		end_tag1=1;
		printf("\n [Parsing]: %s\n", yytext);
		return END_TAG1;} 
	YY_BREAK
/*End tag for </a> is matched here*/
case 7:
YY_RULE_SETUP
#line 79 "tag_parser.l"
{
								//valid endtag
								printf("\n [Parsing]: A end tag: %s\n", yytext);
								return A_END_TAG;	
								
							}
	YY_BREAK
/*Unlnown End tags matched here*/
case 8:
YY_RULE_SETUP
#line 87 "tag_parser.l"
{
								//valid endtag
								printf("\n [Parsing]: %s\n", yytext);
								yyerror("Unknown End Tag.");	
								
							}
	YY_BREAK
/*content inside <a> tag is matched here.*/
case 9:
YY_RULE_SETUP
#line 96 "tag_parser.l"
{
				if(a_valid==1 && end_tag1==1)
				{
					printf("\n [Parsing]: %s\n", yytext);
					return A_CONTENT;
				}
				else
				{
					printf("\n [Parsing]: %s\n", yytext);
 					yyerror("Unknown text.");
 				}

			}
	YY_BREAK
/*attribute src of image tag with attribute value is matched here.*/
case 10:
YY_RULE_SETUP
#line 111 "tag_parser.l"
{	
									
									printf("\n [Parsing] %s\n", yytext);
									return IMG_SRC;
									
								}
	YY_BREAK
/*attribute alt of image tag with attribute value is matched here.*/
case 11:
YY_RULE_SETUP
#line 119 "tag_parser.l"
{	
									
									printf("\n [Parsing]: %s\n", yytext);	
						 			return IMG_ALT;
									
								}
	YY_BREAK
/*all other valid img attributes is matched here*/
case 12:
YY_RULE_SETUP
#line 127 "tag_parser.l"
{
											//valid attribute for img tag
											printf("\n [Parsing]: %s\n", yytext);
								 			return IMG_OTHER_ATTRIBUTE;	
										}	
	YY_BREAK
/*all other attributes which are invalid are matched here*/
case 13:
YY_RULE_SETUP
#line 134 "tag_parser.l"
{
									//attribute list doesnot content this attribute
									printf("\n [Parsing]: %s\n", yytext);
									yyerror("Unknown attribute.");
								}	
	YY_BREAK
/*End tag for image "/>" is matched here*/
case 14:
YY_RULE_SETUP
#line 141 "tag_parser.l"
{
			//valid endtag for img
			printf("\n [Parsing]: %s\n", yytext);
			return IMG_END_TAG2;	
		}
	YY_BREAK
/*End tag for image "></img> is matched here*/
case 15:
YY_RULE_SETUP
#line 149 "tag_parser.l"
{
				//valid endtag
				printf("\n [Parsing]: Image end tag: %s\n", yytext);
				return IMG_END_TAG3;	
				
			}
	YY_BREAK
/*newline character*/
case 16:
YY_RULE_SETUP
#line 157 "tag_parser.l"
{ return NL; }
	YY_BREAK
/*Everything else is matched here.*/
case 17:
YY_RULE_SETUP
#line 160 "tag_parser.l"
{ printf("\n [Parsing]: %s\n", yytext);
 	yyerror("Unknown text.");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 "tag_parser.l"
ECHO;
	YY_BREAK
#line 1020 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 262 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 262 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 261);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 163 "tag_parser.l"


int yywrap()
{
	return 1;
}
